<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        DB::table('order_requests')->insert([
            [
                'name' => 'цифра1',
                'pole' => 'number1',
                'description' => null,
                'number' => 1,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|numeric',
                'deleted_at' => null,
                'created_at' => '2025-05-21 02:16:26',
                'updated_at' => '2025-05-21 02:22:49',
            ],
            [
                'name' => 'цифра2',
                'pole' => 'number2',
                'description' => null,
                'number' => 1,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|integer',
                'deleted_at' => null,
                'created_at' => '2025-05-21 02:38:07',
                'updated_at' => '2025-05-21 02:38:07',
            ],
            [
                'name' => 'цифра4',
                'pole' => 'number4',
                'description' => null,
                'number' => 1,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|integer',
                'deleted_at' => null,
                'created_at' => '2025-05-21 02:38:07',
                'updated_at' => '2025-05-21 02:38:07',
            ],
            [
                'name' => 'цифра5',
                'pole' => 'number5',
                'description' => null,
                'number' => 1,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|integer',
                'deleted_at' => null,
                'created_at' => '2025-05-21 02:38:07',
                'updated_at' => '2025-05-21 02:38:07',
            ],
            [
                'name' => 'цифра6',
                'pole' => 'number6',
                'description' => null,
                'number' => 1,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|integer',
                'deleted_at' => null,
                'created_at' => '2025-05-21 02:38:07',
                'updated_at' => '2025-05-21 02:38:07',
            ],
            [
                'name' => 'Дата1',
                'pole' => 'date1',
                'description' => 'Дата1',
                'number' => 0,
                'date' => 1,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|date',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'Дата2',
                'pole' => 'date2',
                'description' => 'Дата2',
                'number' => 0,
                'date' => 1,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|date',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'Дата3',
                'pole' => 'date3',
                'description' => 'Дата3',
                'number' => 0,
                'date' => 1,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|date',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'Дата4',
                'pole' => 'date4',
                'description' => 'Дата4',
                'number' => 0,
                'date' => 1,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|date',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'датавремя1',
                'pole' => 'dt1',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 1,
                'is_web_link' => 0,
                'rules' => 'nullable|datetime',
                'deleted_at' => null,
                'created_at' => '2025-05-20 21:49:48',
                'updated_at' => '2025-05-20 21:49:48',
            ],
            [
                'name' => 'датавремя2',
                'pole' => 'dt2',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 1,
                'is_web_link' => 0,
                'rules' => 'nullable|datetime',
                'deleted_at' => null,
                'created_at' => '2025-05-20 21:49:48',
                'updated_at' => '2025-05-20 21:49:48',
            ],
            [
                'name' => 'датавремя3',
                'pole' => 'dt3',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 0,
                'nullable' => 1,
                'is_datetime' => 1,
                'is_web_link' => 0,
                'rules' => 'nullable|datetime',
                'deleted_at' => null,
                'created_at' => '2025-05-20 21:49:48',
                'updated_at' => '2025-05-20 21:49:48',
            ],
            [
                'name' => 'строка1',
                'pole' => 'string1',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 1,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|string',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'строка2',
                'pole' => 'string2',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 1,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|string',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'строка3',
                'pole' => 'string3',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 1,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|string',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
            [
                'name' => 'строка4',
                'pole' => 'string4',
                'description' => null,
                'number' => 0,
                'date' => 0,
                'text' => 0,
                'string' => 1,
                'nullable' => 1,
                'is_datetime' => 0,
                'is_web_link' => 0,
                'rules' => 'nullable|string',
                'deleted_at' => null,
                'created_at' => '2025-05-13 03:12:16',
                'updated_at' => '2025-05-13 03:12:16',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Можно удалить записи по полю pole, например:
        DB::table('order_requests')->whereIn('pole', [
            'number1', 'number2', 'number4', 'number5', 'number6',
            'date1', 'date2', 'date3', 'date4',
            'dt1', 'dt2', 'dt3',
            'string1', 'string2', 'string3', 'string4',
        ])->delete();
    }
};
